/*
===============================================================================
02_product_analysis.sql

Purpose
-------
Analyze product-level sales performance, product contribution, transaction
behavior, and product data quality.

Sources
-------
analytics.fact_sales
analytics.dim_product

Fact grain
----------
One row per cleaned transaction line.

Product grain
-------------
One row per stock_code in analytics.dim_product.

Business definitions
--------------------
Gross Sales
    Sales amount generated by Sale transactions.

Net Sales
    Sum of sales_amount across all transaction types.

Units Sold
    Quantity from Sale transactions.

Return Quantity
    Quantity associated with Return transactions.

Cancellation Quantity
    Quantity associated with Cancellation transactions.

Important
---------
Product performance is primarily evaluated using Sale transactions.
Returns and cancellations are analyzed separately so that operational
behavior is not confused with gross sales performance.

Missing product descriptions are retained and explicitly reported rather
than excluded from the analytical model.

===============================================================================
*/


/*
===============================================================================
1. PRODUCT SALES PERFORMANCE
===============================================================================

Core product-level performance metrics.

Only Sale transactions contribute to gross sales and units sold.

===============================================================================
*/

SELECT
    f.stock_code,

    MAX(p.description) AS description,

    COUNT(*) FILTER (
        WHERE f.transaction_type = 'Sale'
    ) AS sale_lines,

    COUNT(DISTINCT f.invoice_no) FILTER (
        WHERE f.transaction_type = 'Sale'
    ) AS sales_invoices,

    SUM(f.quantity) FILTER (
        WHERE f.transaction_type = 'Sale'
    ) AS units_sold,

    SUM(f.sales_amount) FILTER (
        WHERE f.transaction_type = 'Sale'
    ) AS gross_sales,

    SUM(f.sales_amount) AS net_sales,

    AVG(f.unit_price) FILTER (
        WHERE f.transaction_type = 'Sale'
          AND f.unit_price > 0
    ) AS average_selling_price

FROM analytics.fact_sales AS f

LEFT JOIN analytics.dim_product AS p
    ON f.stock_code = p.stock_code

GROUP BY
    f.stock_code

ORDER BY
    gross_sales DESC NULLS LAST;


/*
===============================================================================
2. TOP 20 PRODUCTS BY GROSS SALES
===============================================================================

Management-oriented ranking of the highest-revenue products.

===============================================================================
*/

SELECT
    f.stock_code,

    MAX(p.description) AS description,

    SUM(f.sales_amount) AS gross_sales,

    SUM(f.quantity) AS units_sold,

    COUNT(*) AS sale_lines,

    COUNT(DISTINCT f.invoice_no) AS sales_invoices

FROM analytics.fact_sales AS f

LEFT JOIN analytics.dim_product AS p
    ON f.stock_code = p.stock_code

WHERE f.transaction_type = 'Sale'

GROUP BY
    f.stock_code

ORDER BY
    gross_sales DESC

LIMIT 20;


/*
===============================================================================
3. TOP 20 PRODUCTS BY UNITS SOLD
===============================================================================

Identifies products with the highest physical sales volume.

===============================================================================
*/

SELECT
    f.stock_code,

    MAX(p.description) AS description,

    SUM(f.quantity) AS units_sold,

    SUM(f.sales_amount) AS gross_sales,

    COUNT(*) AS sale_lines,

    COUNT(DISTINCT f.invoice_no) AS sales_invoices

FROM analytics.fact_sales AS f

LEFT JOIN analytics.dim_product AS p
    ON f.stock_code = p.stock_code

WHERE f.transaction_type = 'Sale'

GROUP BY
    f.stock_code

ORDER BY
    units_sold DESC

LIMIT 20;


/*
===============================================================================
4. PRODUCT SALES CONTRIBUTION
===============================================================================

Calculates each product's contribution to total gross sales.

===============================================================================
*/

WITH product_sales AS (
    SELECT
        stock_code,
        SUM(sales_amount) AS gross_sales
    FROM analytics.fact_sales
    WHERE transaction_type = 'Sale'
    GROUP BY stock_code
)

SELECT
    ps.stock_code,

    p.description,

    ps.gross_sales,

    ROUND(
        100.0
        * ps.gross_sales
        / NULLIF(SUM(ps.gross_sales) OVER (), 0),
        2
    ) AS gross_sales_contribution_pct,

    SUM(ps.gross_sales) OVER (
        ORDER BY ps.gross_sales DESC
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS cumulative_gross_sales

FROM product_sales AS ps

LEFT JOIN analytics.dim_product AS p
    ON ps.stock_code = p.stock_code

ORDER BY
    ps.gross_sales DESC;


/*
===============================================================================
5. PRODUCT SALES ABC-STYLE CONTRIBUTION
===============================================================================

Provides cumulative sales contribution bands.

A:
    Products contributing to the first approximately 80% of gross sales.

B:
    Products contributing to the next approximately 15%.

C:
    Remaining products.

This is an analytical segmentation, not an inventory-policy decision.

===============================================================================
*/

WITH product_sales AS (
    SELECT
        stock_code,
        SUM(sales_amount) AS gross_sales
    FROM analytics.fact_sales
    WHERE transaction_type = 'Sale'
    GROUP BY stock_code
),

ranked_products AS (
    SELECT
        stock_code,
        gross_sales,

        SUM(gross_sales) OVER (
            ORDER BY gross_sales DESC
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS cumulative_sales,

        SUM(gross_sales) OVER () AS total_sales

    FROM product_sales
)

SELECT
    rp.stock_code,

    p.description,

    rp.gross_sales,

    ROUND(
        100.0 * rp.gross_sales
        / NULLIF(rp.total_sales, 0),
        2
    ) AS sales_contribution_pct,

    ROUND(
        100.0 * rp.cumulative_sales
        / NULLIF(rp.total_sales, 0),
        2
    ) AS cumulative_sales_pct,

    CASE
        WHEN rp.cumulative_sales
             / NULLIF(rp.total_sales, 0) <= 0.80
            THEN 'A'

        WHEN rp.cumulative_sales
             / NULLIF(rp.total_sales, 0) <= 0.95
            THEN 'B'

        ELSE 'C'
    END AS abc_segment

FROM ranked_products AS rp

LEFT JOIN analytics.dim_product AS p
    ON rp.stock_code = p.stock_code

ORDER BY
    rp.gross_sales DESC;


/*
===============================================================================
6. PRODUCT RETURN AND CANCELLATION BEHAVIOR
===============================================================================

Identifies products associated with returns and cancellations.

===============================================================================
*/

SELECT
    f.stock_code,

    MAX(p.description) AS description,

    COUNT(*) FILTER (
        WHERE f.transaction_type = 'Sale'
    ) AS sale_lines,

    COUNT(*) FILTER (
        WHERE f.transaction_type = 'Return'
    ) AS return_lines,

    COUNT(*) FILTER (
        WHERE f.transaction_type = 'Cancellation'
    ) AS cancellation_lines,

    SUM(f.quantity) FILTER (
        WHERE f.transaction_type = 'Sale'
    ) AS units_sold,

    SUM(f.quantity) FILTER (
        WHERE f.transaction_type = 'Return'
    ) AS returned_quantity,

    SUM(f.quantity) FILTER (
        WHERE f.transaction_type = 'Cancellation'
    ) AS cancelled_quantity,

    SUM(f.sales_amount) FILTER (
        WHERE f.transaction_type = 'Sale'
    ) AS gross_sales,

    SUM(f.sales_amount) FILTER (
        WHERE f.transaction_type = 'Cancellation'
    ) AS cancellation_sales

FROM analytics.fact_sales AS f

LEFT JOIN analytics.dim_product AS p
    ON f.stock_code = p.stock_code

GROUP BY
    f.stock_code

HAVING
    COUNT(*) FILTER (
        WHERE f.transaction_type IN ('Return', 'Cancellation')
    ) > 0

ORDER BY
    cancellation_lines DESC,
    return_lines DESC;


/*
===============================================================================
7. PRODUCT RETURN RATE
===============================================================================

Return rate based on transaction-line counts.

Only products with at least one Sale transaction are included.

===============================================================================
*/

WITH product_activity AS (
    SELECT
        stock_code,

        COUNT(*) FILTER (
            WHERE transaction_type = 'Sale'
        ) AS sale_lines,

        COUNT(*) FILTER (
            WHERE transaction_type = 'Return'
        ) AS return_lines

    FROM analytics.fact_sales

    GROUP BY stock_code
)

SELECT
    pa.stock_code,

    p.description,

    pa.sale_lines,

    pa.return_lines,

    ROUND(
        100.0 * pa.return_lines
        / NULLIF(pa.sale_lines, 0),
        2
    ) AS return_rate_pct

FROM product_activity AS pa

LEFT JOIN analytics.dim_product AS p
    ON pa.stock_code = p.stock_code

WHERE pa.sale_lines > 0

ORDER BY
    return_rate_pct DESC,
    pa.return_lines DESC;


/*
===============================================================================
8. PRODUCT CANCELLATION RATE
===============================================================================

Cancellation rate based on transaction-line counts.

===============================================================================
*/

WITH product_activity AS (
    SELECT
        stock_code,

        COUNT(*) FILTER (
            WHERE transaction_type = 'Sale'
        ) AS sale_lines,

        COUNT(*) FILTER (
            WHERE transaction_type = 'Cancellation'
        ) AS cancellation_lines

    FROM analytics.fact_sales

    GROUP BY stock_code
)

SELECT
    pa.stock_code,

    p.description,

    pa.sale_lines,

    pa.cancellation_lines,

    ROUND(
        100.0 * pa.cancellation_lines
        / NULLIF(pa.sale_lines, 0),
        2
    ) AS cancellation_rate_pct

FROM product_activity AS pa

LEFT JOIN analytics.dim_product AS p
    ON pa.stock_code = p.stock_code

WHERE pa.sale_lines > 0

ORDER BY
    cancellation_rate_pct DESC,
    pa.cancellation_lines DESC;


/*
===============================================================================
9. PRODUCTS WITH MISSING DESCRIPTIONS
===============================================================================

Documents product master-data quality.

These products remain in the analytical model.

===============================================================================
*/

SELECT
    p.stock_code,

    p.description

FROM analytics.dim_product AS p

WHERE p.description IS NULL
   OR TRIM(p.description) = ''

ORDER BY
    p.stock_code;


/*
===============================================================================
10. PRODUCT DATA-QUALITY SUMMARY
===============================================================================

Provides a compact product-master quality overview.

===============================================================================
*/

SELECT
    COUNT(*) AS total_products,

    COUNT(*) FILTER (
        WHERE description IS NULL
           OR TRIM(description) = ''
    ) AS products_without_description,

    COUNT(*) FILTER (
        WHERE description IS NOT NULL
          AND TRIM(description) <> ''
    ) AS products_with_description

FROM analytics.dim_product;


/*
===============================================================================
11. PRODUCT ACTIVITY BY YEAR
===============================================================================

Tracks product sales performance across years.

===============================================================================
*/

SELECT
    EXTRACT(YEAR FROM f.invoice_date)::INTEGER AS sales_year,

    f.stock_code,

    MAX(p.description) AS description,

    SUM(f.quantity) AS units_sold,

    SUM(f.sales_amount) AS gross_sales,

    COUNT(DISTINCT f.invoice_no) AS sales_invoices

FROM analytics.fact_sales AS f

LEFT JOIN analytics.dim_product AS p
    ON f.stock_code = p.stock_code

WHERE f.transaction_type = 'Sale'

GROUP BY
    EXTRACT(YEAR FROM f.invoice_date),
    f.stock_code

ORDER BY
    sales_year,
    gross_sales DESC;


/*
===============================================================================
12. PRODUCT PERFORMANCE RANKING
===============================================================================

Ranks products using gross sales, units sold, and invoice reach.

===============================================================================
*/

WITH product_metrics AS (
    SELECT
        stock_code,

        SUM(sales_amount) AS gross_sales,

        SUM(quantity) AS units_sold,

        COUNT(DISTINCT invoice_no) AS sales_invoices

    FROM analytics.fact_sales

    WHERE transaction_type = 'Sale'

    GROUP BY
        stock_code
)

SELECT
    pm.stock_code,

    p.description,

    pm.gross_sales,

    pm.units_sold,

    pm.sales_invoices,

    RANK() OVER (
        ORDER BY pm.gross_sales DESC
    ) AS revenue_rank,

    RANK() OVER (
        ORDER BY pm.units_sold DESC
    ) AS volume_rank,

    RANK() OVER (
        ORDER BY pm.sales_invoices DESC
    ) AS invoice_reach_rank

FROM product_metrics AS pm

LEFT JOIN analytics.dim_product AS p
    ON pm.stock_code = p.stock_code

ORDER BY
    revenue_rank;


/*
===============================================================================
13. LOW-VOLUME PRODUCTS
===============================================================================

Identifies products with limited sales activity.

Useful for assortment and product-performance analysis.

===============================================================================
*/

SELECT
    f.stock_code,

    MAX(p.description) AS description,

    COUNT(*) AS sale_lines,

    SUM(f.quantity) AS units_sold,

    SUM(f.sales_amount) AS gross_sales,

    COUNT(DISTINCT f.invoice_no) AS sales_invoices

FROM analytics.fact_sales AS f

LEFT JOIN analytics.dim_product AS p
    ON f.stock_code = p.stock_code

WHERE f.transaction_type = 'Sale'

GROUP BY
    f.stock_code

HAVING
    COUNT(*) <= 5

ORDER BY
    gross_sales DESC;


/*
===============================================================================
14. PRODUCT PERFORMANCE SUMMARY
===============================================================================

Compact product-level KPI baseline for downstream reporting.

===============================================================================
*/

SELECT
    COUNT(DISTINCT f.stock_code) AS products_with_transactions,

    COUNT(DISTINCT f.stock_code) FILTER (
        WHERE f.transaction_type = 'Sale'
    ) AS products_with_sales,

    SUM(f.quantity) FILTER (
        WHERE f.transaction_type = 'Sale'
    ) AS total_units_sold,

    SUM(f.sales_amount) FILTER (
        WHERE f.transaction_type = 'Sale'
    ) AS total_gross_sales,

    COUNT(DISTINCT f.invoice_no) FILTER (
        WHERE f.transaction_type = 'Sale'
    ) AS total_sales_invoices

FROM analytics.fact_sales AS f;